name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: macos-26

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: SwiftFormat Check
        run: |
          brew install swiftformat || true
          swiftformat . --config .swiftformat --lint

      - name: SwiftLint
        run: |
          brew install swiftlint || true
          swiftlint --config .swiftlint.yml --strict

      - name: Generate secrets file
        run: |
          cat <<EOF > IsItRainingInTheUK/OpenWeatherMapAPI+Ext.swift
          extension OpenWeatherMapAPI {
              static let key = "${{ secrets.OPENWEATHERMAP_API_KEY }}"
          }
          EOF

      - name: Build & Test
        run: |
          xcodebuild clean build test \
            -project "IsItRainingInTheUK.xcodeproj" \
            -scheme "CI" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      